// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesserChat.Server.Persistence;

#nullable disable

namespace TesserChat.Server.Persistence.Migrations
{
    [DbContext(typeof(TesserChatDbContext))]
    [Migration("20260825082321_SessionTokenSigningKeys")]
    partial class SessionTokenSigningKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesserChat.Server.Persistence.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<byte[]>("EncryptionKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_key")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<byte[]>("SigningKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("signing_key")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("SigningKey")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_signing_key");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("AccountId", "RoleId")
                        .HasName("pk_account_roles");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_roles_account_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_account_roles_role_id");

                    b.ToTable("account_roles", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_id");

                    b.Property<Guid?>("TargetRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_role_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorAccountId")
                        .HasDatabaseName("ix_audit_entries_actor_account_id");

                    b.HasIndex("TargetAccountId")
                        .HasDatabaseName("ix_audit_entries_target_account_id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.LoginNonce", b =>
                {
                    b.Property<byte[]>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("value")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.HasKey("Value")
                        .HasName("pk_login_nonces");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_nonces_expires_at");

                    b.ToTable("login_nonces", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.PermissionGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.HasKey("Key")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "members.kick",
                            Description = "Remove a member from this server."
                        },
                        new
                        {
                            Key = "members.ban",
                            Description = "Ban a member and prevent that key from registering again."
                        },
                        new
                        {
                            Key = "roles.manage",
                            Description = "Create, edit, and delete roles and the permissions they grant."
                        },
                        new
                        {
                            Key = "roles.assign",
                            Description = "Assign roles to members and remove them."
                        },
                        new
                        {
                            Key = "messages.delete",
                            Description = "Delete messages posted by other members."
                        },
                        new
                        {
                            Key = "server.manage",
                            Description = "Change server settings, including how new members may join."
                        },
                        new
                        {
                            Key = "auditlog.read",
                            Description = "Read the record of moderation and administration actions."
                        });
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("IsOwner")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_single_owner")
                        .HasFilter("is_owner");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7b20ae6-0d3b-86ec-9559-d159581d70c5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOwner = true,
                            IsSystemRole = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOwner = false,
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bd8ddf38-0605-8dd8-bc39-fed582c9b020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOwner = false,
                            IsSystemRole = true,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_key");

                    b.HasKey("RoleId", "PermissionKey")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionKey")
                        .HasDatabaseName("ix_role_permissions_permission_key");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            PermissionKey = "members.kick"
                        },
                        new
                        {
                            RoleId = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            PermissionKey = "members.ban"
                        },
                        new
                        {
                            RoleId = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            PermissionKey = "roles.assign"
                        },
                        new
                        {
                            RoleId = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            PermissionKey = "messages.delete"
                        },
                        new
                        {
                            RoleId = new Guid("9a4d151d-c7d9-8580-b363-66b8bc7b19e0"),
                            PermissionKey = "auditlog.read"
                        });
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("SetUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_up_at");

                    b.Property<Guid>("SetUpByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_up_by_account_id");

                    b.Property<bool>("singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("singleton")
                        .HasDefaultValueSql("true");

                    b.HasKey("Id")
                        .HasName("pk_server_instances");

                    b.HasIndex("singleton")
                        .IsUnique()
                        .HasDatabaseName("ix_server_instances_singleton");

                    b.ToTable("server_instances", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.TokenSigningKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("secret")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_token_signing_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_token_signing_keys_created_at");

                    b.ToTable("token_signing_keys", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.AccountRole", b =>
                {
                    b.HasOne("TesserChat.Server.Persistence.Account", "Account")
                        .WithMany("Roles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_roles_accounts_account_id");

                    b.HasOne("TesserChat.Server.Persistence.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_roles_roles_role_id");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.RolePermission", b =>
                {
                    b.HasOne("TesserChat.Server.Persistence.PermissionGrant", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_key");

                    b.HasOne("TesserChat.Server.Persistence.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.Account", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.PermissionGrant", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.Role", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
