// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesserChat.Server.Persistence;

#nullable disable

namespace TesserChat.Server.Persistence.Migrations
{
    [DbContext(typeof(TesserChatDbContext))]
    [Migration("20260824080104_AccountRegistration")]
    partial class AccountRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesserChat.Server.Persistence.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<byte[]>("EncryptionKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("encryption_key")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<byte[]>("SigningKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("signing_key")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("SigningKey")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_signing_key");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TesserChat.Server.Persistence.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_server_instances");

                    b.ToTable("server_instances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
