namespace TesserChat.Server.Persistence;

/// <summary>
/// The secret this server signs session tokens with (§4.7.6).
/// </summary>
/// <remarks>
/// <para>
/// <b>Generated by the server, never configured.</b> A signing key is high-entropy random material
/// that no human needs to read, type, or choose — so asking an operator to supply one only creates
/// ways for it to be weak, shared between deployments, committed to a repository, or left at
/// whatever the example file suggested. The server makes its own on first use and an operator never
/// handles it at all.
/// </para>
/// <para>
/// <b>In the database rather than a file</b>, because the database is already the thing a
/// deployment must persist and back up. A key in a mounted file is one more piece of state a
/// self-hoster can lose while believing their backup is complete, and losing it silently
/// invalidates every outstanding session.
/// </para>
/// <para>
/// <b>Not part of <see cref="ServerInstance"/>, deliberately.</b> That row is the server's public
/// identity and is read on every login to scope a challenge; this is a secret read only when a
/// token is signed or verified. Keeping them in separate tables means a query that wants the
/// server's id cannot accidentally carry its signing key along with it.
/// </para>
/// <para>
/// Rotation is supported by rows rather than by overwriting: several keys may exist, the newest
/// signs, and any unexpired key verifies. See <c>TokenSigningKeyStore</c> for why that matters —
/// overwriting one key in place would invalidate every session on the instant it happened.
/// </para>
/// </remarks>
internal sealed class TokenSigningKey
{
    /// <summary>Length of the secret, in bytes.</summary>
    /// <remarks>
    /// 32 bytes for HMAC-SHA256, matching the hash's output size. Longer buys nothing — HMAC folds
    /// a key longer than its block size back down by hashing it — and shorter reduces the work an
    /// attacker must do to forge a token.
    /// </remarks>
    public const int SecretSize = 32;

    /// <summary>Identifies this key, and travels in the token's <c>kid</c> header.</summary>
    /// <remarks>
    /// So verification can select the right key directly rather than trying every key it holds. A
    /// <c>kid</c> is not a secret and not a trust signal: it says which key to try, and the
    /// signature check is what decides whether that was the right answer.
    /// </remarks>
    public Guid Id { get; init; }

    /// <summary>The HMAC secret itself.</summary>
    public byte[] Secret { get; init; } = [];

    /// <summary>When this key was generated.</summary>
    /// <remarks>
    /// Which key signs is decided by this: the newest one. So a rotation takes effect by inserting a
    /// row, with no update to the row it supersedes.
    /// </remarks>
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// When this key stops being accepted for verification, or <see langword="null"/> while it is
    /// current.
    /// </summary>
    /// <remarks>
    /// Set when a newer key supersedes this one, to the moment the last token it could have signed
    /// expires. Until then it must still verify, or rotating would log out every member holding a
    /// perfectly valid token. After then it is dead weight and the sweep removes it.
    /// </remarks>
    public DateTimeOffset? RetiredAt { get; set; }
}
