using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using TesserChat.Server.Persistence;

namespace TesserChat.Server.Auth;

/// <summary>
/// Supplies the secret session tokens are signed and verified with (§4.7.6).
/// </summary>
/// <remarks>
/// <para>
/// <b>The key is generated on first use, not configured.</b> An operator never sees it, which is
/// the point: nobody can pick a weak one, paste the example file's value into production, or share
/// one between two deployments that should not trust each other's tokens.
/// </para>
/// <para>
/// <b>Cached in memory, because verification runs on every authenticated request.</b> Reading a row
/// per request would put the database on the path of every call, including the ones that do not
/// otherwise touch it. The cache is only ever added to — a key's secret never changes once written —
/// so a stale entry cannot verify a token incorrectly; it can only fail to know about a key added
/// by another instance, which is handled by falling through to the database on a miss.
/// </para>
/// <para>
/// <b>Singleton, unlike the rest of the auth services.</b> The cache is process-wide by design, so
/// this resolves its own scope per database read rather than holding a scoped
/// <c>TesserChatDbContext</c> it would outlive.
/// </para>
/// </remarks>
internal sealed class TokenSigningKeyStore(
    IServiceScopeFactory scopeFactory,
    TimeProvider timeProvider,
    ILogger<TokenSigningKeyStore> logger)
{
    /// <summary>
    /// Keys by id, for verification. Never removed while the process lives — a retired key must
    /// still verify tokens it signed, and an entry costs 32 bytes.
    /// </summary>
    private readonly Dictionary<Guid, byte[]> _byId = [];

    /// <summary>
    /// Serialises first-use generation, so two simultaneous logins on a fresh server do not both
    /// decide the database is empty and both insert a key.
    /// </summary>
    private readonly SemaphoreSlim _gate = new(1, 1);

    private SigningKeyMaterial? _current;

    /// <summary>
    /// The key to sign new tokens with, generating one if this server has never signed before.
    /// </summary>
    public async Task<SigningKeyMaterial> GetSigningKeyAsync(
        CancellationToken cancellationToken = default)
    {
        var cached = _current;
        if (cached is not null)
        {
            return cached;
        }

        await _gate.WaitAsync(cancellationToken);
        try
        {
            // Re-checked inside the gate: another caller may have generated one while this call
            // waited, and generating a second would orphan the tokens the first had already signed.
            if (_current is not null)
            {
                return _current;
            }

            await using var scope = scopeFactory.CreateAsyncScope();
            var context = scope.ServiceProvider.GetRequiredService<TesserChatDbContext>();

            var existing = await context.TokenSigningKeys
                .AsNoTracking()
                .Where(key => key.RetiredAt == null)
                .OrderByDescending(key => key.CreatedAt)
                .FirstOrDefaultAsync(cancellationToken);

            existing ??= await GenerateAsync(context, cancellationToken);

            Remember(existing.Id, existing.Secret);
            _current = new SigningKeyMaterial(existing.Id, existing.Secret);

            return _current;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// The secret for <paramref name="keyId"/>, or <see langword="null"/> if this server has no
    /// such key.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Called per token validation, so the cache hit is the path that matters. A miss falls through
    /// to the database to cover a key generated by another instance sharing this database — without
    /// that, a two-instance deployment would reject perfectly valid tokens depending on which
    /// instance answered.
    /// </para>
    /// <para>
    /// <b>Returning a key is not a decision that the token is good.</b> This says only which secret
    /// to check against; the signature check is what establishes anything, and it happens after.
    /// </para>
    /// </remarks>
    public async Task<byte[]?> FindVerificationKeyAsync(
        Guid keyId,
        CancellationToken cancellationToken = default)
    {
        lock (_byId)
        {
            if (_byId.TryGetValue(keyId, out var cached))
            {
                return cached;
            }
        }

        await using var scope = scopeFactory.CreateAsyncScope();
        var context = scope.ServiceProvider.GetRequiredService<TesserChatDbContext>();

        var key = await context.TokenSigningKeys
            .AsNoTracking()
            .SingleOrDefaultAsync(candidate => candidate.Id == keyId, cancellationToken);

        if (key is null)
        {
            // Ordinary for a token issued by a different server, which §4.7.6 expects to see on a
            // network of independent deployments. Not evidence of an attack by itself.
            return null;
        }

        // A retired key still verifies until its retirement instant passes: tokens it signed remain
        // valid for their own lifetime, and rotating should not log anybody out.
        if (key.RetiredAt is { } retiredAt && retiredAt <= timeProvider.GetUtcNow())
        {
            return null;
        }

        Remember(key.Id, key.Secret);
        return key.Secret;
    }

    /// <summary>
    /// Generates this server's first signing key.
    /// </summary>
    /// <remarks>
    /// Concurrent first-use across two instances is resolved by the primary key rather than by
    /// timing: both may insert, one loses, and the loser re-reads the winner's row. Which key wins
    /// does not matter — only that the server settles on one.
    /// </remarks>
    private async Task<TokenSigningKey> GenerateAsync(
        TesserChatDbContext context,
        CancellationToken cancellationToken)
    {
        var key = new TokenSigningKey
        {
            Id = Guid.CreateVersion7(),
            Secret = RandomNumberGenerator.GetBytes(TokenSigningKey.SecretSize),
            CreatedAt = timeProvider.GetUtcNow(),
        };

        context.TokenSigningKeys.Add(key);

        try
        {
            await context.SaveChangesAsync(cancellationToken);

            logger.LogInformation(
                "Generated this server's session token signing key. Sessions issued under it stay "
                + "valid only while this database does.");

            return key;
        }
        catch (DbUpdateException)
        {
            // Another instance got there first. Take theirs — two keys would work, but settling on
            // one keeps `kid` lookups warm on both instances.
            context.ChangeTracker.Clear();

            var winner = await context.TokenSigningKeys
                .AsNoTracking()
                .Where(candidate => candidate.RetiredAt == null)
                .OrderByDescending(candidate => candidate.CreatedAt)
                .FirstOrDefaultAsync(cancellationToken);

            if (winner is null)
            {
                // The insert failed for a reason other than a race, so there is nothing to fall
                // back to and signing cannot proceed.
                throw;
            }

            return winner;
        }
    }

    private void Remember(Guid keyId, byte[] secret)
    {
        lock (_byId)
        {
            _byId[keyId] = secret;
        }
    }
}

/// <summary>
/// A signing key and the id that identifies it in a token's <c>kid</c> header.
/// </summary>
internal sealed record SigningKeyMaterial(Guid Id, byte[] Secret);
